version: '3.1'

services:
  api:
    build: .
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
      - es
    environment:
      DB_NAME: euromedik
      DB_USER: euromedik
      DB_PASS: v3rys3cr3t
      DB_HOST: db
      ES_HOST: "es:9200"
    volumes:
      - .:/code
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: 'v3rys3cr3t'
      POSTGRES_USER: 'euromedik'
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
  es:
    image: elasticsearch:7.3.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=euromk-cluster-local
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.type=single-node
    volumes:
      - ./es_data:/usr/share/elasticsearch/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080
