# Generated by Django 2.2.6 on 2019-10-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0002_auto_20191008_2229")]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="slug",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, unique=True
            ),
        ),
    ]
