# Generated by Django 2.2.6 on 2019-11-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0005_auto_20191013_1656")]

    operations = [
        migrations.AddField(
            model_name="category",
            name="ordering_id",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="service",
            name="ordering_id",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
