# Generated by Django 2.2.6 on 2019-11-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0006_auto_20191114_2234")]

    operations = [
        migrations.CreateModel(
            name="Bundle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("ordering_id", models.PositiveSmallIntegerField(default=0)),
            ],
            options={"ordering": ["ordering_id"]},
        )
    ]
