# Generated by Django 2.2.6 on 2019-11-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0007_bundle")]

    operations = [
        migrations.AddField(
            model_name="location",
            name="maps_url",
            field=models.TextField(blank=True, max_length=1000, null=True),
        )
    ]
