# Generated by Django 2.2.6 on 2019-11-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0008_location_maps_url")]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="small_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        )
    ]
