# Generated by Django 2.2.6 on 2019-11-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0010_auto_20191126_2223")]

    operations = [
        migrations.RemoveField(model_name="category", name="icon"),
        migrations.AddField(
            model_name="category",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
