# Generated by Django 2.2.6 on 2019-12-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0011_auto_20191126_2258")]

    operations = [
        migrations.AddField(
            model_name="service",
            name="price_extra",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Upper price. Leave empty if no price range",
            ),
        )
    ]
