# Generated by Django 2.2.6 on 2019-12-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0012_service_price_extra")]

    operations = [
        migrations.AddField(
            model_name="service",
            name="blog_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        )
    ]
