# Generated by Django 2.2.6 on 2019-12-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0013_service_blog_link")]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="blog_link",
            field=models.CharField(blank=True, max_length=500, null=True),
        )
    ]
