# Generated by Django 2.2.4 on 2019-12-03 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0014_auto_20191203_1135")]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="workhours", options={"verbose_name_plural": "Work Hours"}
        ),
        migrations.AddField(
            model_name="bundle",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.Service",
            ),
        ),
    ]
