# Generated by Django 2.2.4 on 2020-05-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0018_add_doctors")]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="slug",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, unique=True
            ),
        )
    ]
