# Generated by Django 2.2.4 on 2020-05-11 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0019_add_slug_to_doctors")]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="reference",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="references",
                to="core.Doctor",
            ),
        ),
    ]
