# Generated by Django 2.2.4 on 2020-05-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0022_auto_20200521_0010")]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="biography",
            field=models.TextField(max_length=2000),
        )
    ]
