# Generated by Django 2.2.4 on 2020-08-11 21:15

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [("core", "0023_extend_biography_length")]

    operations = [
        migrations.RemoveField(model_name="doctor", name="services"),
        migrations.AddField(
            model_name="doctor",
            name="services",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
