# Generated by Django 2.2.4 on 2020-08-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0024_convert_doctors_services_to_list")]

    operations = [
        migrations.AddField(
            model_name="category",
            name="doctors_ordering_id",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="doctor",
            name="ordering_id",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
