# Generated by Django 2.2.4 on 2020-12-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0026_price_on_demand")]

    operations = [
        migrations.RemoveField(model_name="phonenumber", name="category"),
        migrations.AddField(
            model_name="hospital",
            name="contact_info",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
