# Generated by Django 2.2.4 on 2021-02-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_hospital_contact_info_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ['ordering_id', 'id']},
        ),
        migrations.AddField(
            model_name='hospital',
            name='ordering_id',
            field=models.PositiveSmallIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='contact_info',
            field=models.TextField(blank=True, help_text='Use this to present any additional contact info below the phone numbers. HTML Safe', max_length=1000, null=True),
        ),
    ]
